# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

from __future__ import annotations

import collections
import collections.abc
import json
import logging
import sys
from abc import ABCMeta
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, fields, is_dataclass, replace
from typing import Any, Protocol, runtime_checkable

from pants.core.goals.deploy import Deploy, DeployFieldSet
from pants.core.goals.package import Package, PackageFieldSet
from pants.core.goals.publish import Publish, PublishFieldSet
from pants.core.goals.run import Run, RunFieldSet
from pants.core.goals.test import Test, TestFieldSet
from pants.engine.addresses import Address, Addresses
from pants.engine.collection import Collection
from pants.engine.console import Console
from pants.engine.environment import ChosenLocalEnvironmentName, EnvironmentName
from pants.engine.fs import PathGlobsBatch, Snapshot
from pants.engine.goal import Goal, GoalSubsystem, Outputting
from pants.engine.internals.build_files import (
    _get_target_family_and_adaptor_for_dep_rules,
    get_dependencies_rule_application,
)
from pants.engine.internals.dep_rules import DependencyRuleApplication, DependencyRuleSet
from pants.engine.internals.graph import (
    expand_targets_in_bulk,
    filter_targets,
    hydrate_sources,
    resolve_dependencies_bulk,
    resolve_targets,
)
from pants.engine.intrinsics import path_globs_to_snapshots
from pants.engine.rules import Rule, collect_rules, concurrently, goal_rule, implicitly, rule
from pants.engine.target import (
    AlwaysTraverseDeps,
    BulkDependenciesRequest,
    Dependencies,
    DependenciesRequest,
    DependenciesRuleApplicationRequest,
    Field,
    FieldSet,
    ImmutableValue,
    InferDependenciesRequest,
    SourcesField,
    Target,
    Targets,
    TargetTypesToGenerateTargetsRequests,
    UnexpandedTargets,
    applicable_field_set_types,
)
from pants.engine.unions import UnionMembership, union
from pants.option.bootstrap_options import UnmatchedBuildFileGlobs
from pants.option.option_types import BoolOption
from pants.util.frozendict import FrozenDict
from pants.util.strutil import softwrap

logger = logging.getLogger(__name__)


@runtime_checkable
class Dictable(Protocol):
    """Make possible to avoid adding concrete types to serialize objects."""

    def asdict(self) -> Mapping[str, Any]: ...


class PeekSubsystem(Outputting, GoalSubsystem):
    """Display detailed target information in JSON form."""

    name = "peek"
    help = "Display BUILD target info"

    exclude_defaults = BoolOption(
        default=False,
        help="Whether to leave off values that match the target-defined default values.",
    )

    include_dep_rules = BoolOption(
        default=False,
        help=softwrap(
            """
            Whether to include `_dependencies_rules`, `_dependents_rules` and `_applicable_dep_rules`
            that apply to the target and its dependencies.
            """
        ),
    )

    include_additional_info = BoolOption(
        default=False, help="Whether to include additional information generated by plugins."
    )


class Peek(Goal):
    subsystem_cls = PeekSubsystem
    environment_behavior = Goal.EnvironmentBehavior.LOCAL_ONLY


_SCALAR_TYPES = frozenset({str, int, float, bool, type(None), tuple})


def _normalize_value(val: Any) -> Any:
    if type(val) in _SCALAR_TYPES:
        return val
    if isinstance(val, collections.abc.Mapping):
        return {str(k): _normalize_value(v) for k, v in val.items()}
    return val


@union(in_scope_types=[EnvironmentName])
@dataclass(frozen=True)
class HasAdditionalTargetDataFieldSet(FieldSet, metaclass=ABCMeta):
    """Union type to attach data to a target that will appear under the "additional_info" field in
    the output of `pants peek` if the `--peek-include-additional-info` option is enabled."""


@union(in_scope_types=[EnvironmentName])
@dataclass(frozen=True)
class PeekBulkDependenciesRequest:
    """A backend may compute the direct dependencies of many targets at once for `peek`.

    Implementations return, for each target they handle, exactly the `Addresses` which resolving a
    `DependenciesRequest` (always traversing) for it would, with dependency validation applied.
    Targets which an implementation does not handle are resolved individually. `targets` are always
    among the implementation's `candidates`.
    """

    targets: tuple[Target, ...]

    @classmethod
    def candidates(
        cls, targets: Iterable[Target], union_membership: UnionMembership
    ) -> tuple[Target, ...]:
        """The targets this implementation may handle, which are then not resolved individually
        unless it declines them.

        Must be cheap: it runs before any dependency resolution starts.
        """
        return ()


@dataclass(frozen=True)
class PeekBulkDependencies:
    dependencies: FrozenDict[Address, Addresses]


@rule(polymorphic=True)
async def get_peek_bulk_dependencies(request: PeekBulkDependenciesRequest) -> PeekBulkDependencies:
    raise NotImplementedError()


@dataclass(frozen=True)
class AdditionalTargetData:
    label: str
    data: ImmutableValue

    def __init__(self, label: str, data: Any) -> None:
        object.__setattr__(self, "label", label)
        if isinstance(data, collections.abc.Mapping):
            data = FrozenDict.deep_freeze(data)
        elif isinstance(data, (list, set)):
            data = tuple(data)
        object.__setattr__(self, "data", data)


@rule(polymorphic=True)
async def get_additional_target_data(
    field_set: HasAdditionalTargetDataFieldSet, env_name: EnvironmentName
) -> AdditionalTargetData:
    raise NotImplementedError()


class _Unset:
    pass


_UNSET = _Unset()


@dataclass(frozen=True)
class TargetData:
    target: Target
    # Sources may not be registered on the target, so we'll have nothing to expand.
    expanded_sources: Snapshot | None
    expanded_dependencies: tuple[str, ...]

    dependencies_rules: tuple[str, ...] | None = None
    dependents_rules: tuple[str, ...] | None = None
    applicable_dep_rules: tuple[DependencyRuleApplication, ...] | None = None
    goals: tuple[str, ...] | None = None
    additional_info: tuple[AdditionalTargetData, ...] | None = None

    def to_dict(
        self,
        exclude_defaults: bool = False,
        include_dep_rules: bool = False,
        goals: tuple[str, ...] | None | _Unset = _UNSET,
    ) -> dict:
        """The target data as a JSON-compatible dict, with `goals` in place of `self.goals` if
        given."""
        nothing = object()
        fields = {}
        for k, v in self.target.field_values.items():
            value = v.value
            if exclude_defaults and getattr(k, "default", nothing) == value:
                continue
            key = _FIELD_OUTPUT_KEYS.get(k)
            if key is None:
                key = _field_output_key(k)
            fields[key] = value if type(value) in _SCALAR_TYPES else _normalize_value(value)

        fields["dependencies"] = self.expanded_dependencies
        if self.expanded_sources is not None:
            fields["sources"] = self.expanded_sources.files
            fields["sources_fingerprint"] = self.expanded_sources.digest.fingerprint

        if include_dep_rules:
            fields["_dependencies_rules"] = self.dependencies_rules
            fields["_dependents_rules"] = self.dependents_rules
            fields["_applicable_dep_rules"] = self.applicable_dep_rules

        if goals is _UNSET:
            goals = self.goals
        if goals is not None:
            fields["goals"] = goals

        if self.additional_info is not None:
            fields["additional_info"] = {
                additional_target_data.label: additional_target_data.data
                for additional_target_data in sorted(
                    self.additional_info, key=lambda atd: atd.label
                )
            }

        result = {
            "address": self.target.address.spec,
            "target_type": self.target.alias,
        }
        result.update(sorted(fields.items()))
        return result


_FIELD_OUTPUT_KEYS: dict[type[Field], str] = {}


def _field_output_key(field_type: type[Field]) -> str:
    key = _FIELD_OUTPUT_KEYS.get(field_type)
    if key is None:
        key = (
            f"{field_type.alias}_raw"
            if issubclass(field_type, (SourcesField, Dependencies))
            else field_type.alias
        )
        _FIELD_OUTPUT_KEYS[field_type] = key
    return key


_FIELD_OUTPUT_KEYS: dict[type[Field], str] = {}


def _field_output_key(field_type: type[Field]) -> str:
    key = _FIELD_OUTPUT_KEYS.get(field_type)
    if key is None:
        key = (
            f"{field_type.alias}_raw"
            if issubclass(field_type, (SourcesField, Dependencies))
            else field_type.alias
        )
        _FIELD_OUTPUT_KEYS[field_type] = key
    return key


class TargetDatas(Collection[TargetData]):
    pass


def render_json(
    tds: Iterable[TargetData],
    exclude_defaults: bool = False,
    include_dep_rules: bool = False,
    *,
    goals_by_alias: Mapping[str, tuple[str, ...]] | None = None,
) -> str:
    """Renders the target data, with the goals of each target taken from `goals_by_alias` if
    given (as if each `TargetData` had its `goals` set from it)."""
    if goals_by_alias is None:
        dicts = [td.to_dict(exclude_defaults, include_dep_rules) for td in tds]
    else:
        dicts = [
            td.to_dict(
                exclude_defaults, include_dep_rules, goals=goals_by_alias.get(td.target.alias)
            )
            for td in tds
        ]
    return f"{json.dumps(dicts, indent=2, cls=_PeekJsonEncoder)}\n"


class _PeekJsonEncoder(json.JSONEncoder):
    """Allow us to serialize some commonly found types in BUILD files."""

    def default(self, o):
        """Return a serializable object for o."""
        if isinstance(o, str):  # early exit prevents strings from being treated as sequences
            return o
        if o is None:
            return o
        if is_dataclass(o):
            # NB: `dataclasses.asdict` creates a deep copy by default, which is unnecessary for
            # this case.
            return {field.name: getattr(o, field.name) for field in fields(o)}
        if isinstance(o, collections.abc.Mapping):
            return dict(o)
        if (
            isinstance(o, collections.abc.Sequence)
            or isinstance(o, set)
            or isinstance(o, collections.abc.Set)
        ):
            return list(o)
        if isinstance(o, Field):
            return self.default(o.value)
        if isinstance(o, Dictable):
            return o.asdict()
        try:
            return super().default(o)
        except TypeError:
            return str(o)


def describe_ruleset(ruleset: DependencyRuleSet | None) -> tuple[str, ...] | None:
    if ruleset is None:
        return None
    return ruleset.peek()


async def _create_target_alias_to_goals_map(
    union_membership: UnionMembership,
) -> dict[str, tuple[str, ...]]:
    """Returns a mapping from a target alias to the goals that can operate on that target.

    For instance, `pex_binary` would map to `("run", "package")`.

    A goal is attributed to an alias if any target root of that type has an applicable
    implementation of the goal's field set, which is what computing the field sets of every target
    root for every goal would determine.

    :return: A mapping from a target alias to the goals that can operate on that target.
    """
    # This is manually curated for now - we'll have to use it a bit to determine if we want to show all goals or not
    field_set_to_goal_map: dict[type[FieldSet], str] = {
        DeployFieldSet: Deploy.name,
        PackageFieldSet: Package.name,
        PublishFieldSet: Publish.name,
        RunFieldSet: Run.name,
        TestFieldSet: Test.name,
    }

    targets = await filter_targets(**implicitly())
    targets_by_type: dict[type[Target], list[Target]] = collections.defaultdict(list)
    for tgt in targets:
        targets_by_type[type(tgt)].append(tgt)

    alias_to_goals_map: dict[str, set[str]] = {}
    for field_set_superclass, goal in field_set_to_goal_map.items():
        implementations = union_membership.get(field_set_superclass)
        for tgt_type, tgts in targets_by_type.items():
            candidates = [
                implementation
                for implementation in implementations
                if tgt_type.class_has_fields(implementation.required_fields, union_membership)
            ]
            if candidates and any(
                implementation.is_applicable(tgt) for tgt in tgts for implementation in candidates
            ):
                alias_to_goals_map.setdefault(tgt_type.alias, set()).add(goal)

    # Convert the goal sets to tuples for JSON serialization
    return {alias: tuple(sorted(goals)) for alias, goals in alias_to_goals_map.items()}


@rule
async def get_target_data(
    targets: UnexpandedTargets,
    subsys: PeekSubsystem,
    union_membership: UnionMembership,
    target_types_to_generate_requests: TargetTypesToGenerateTargetsRequests,
    local_environment_name: ChosenLocalEnvironmentName,
    unmatched_build_file_globs: UnmatchedBuildFileGlobs,
) -> TargetDatas:
    """Given a set of unexpanded targets, return a mapping of target addresses to their data.

    The data includes the target's fields, expanded sources, expanded dependencies, and any
    dependency rules that apply to the target.

    NB: We must preserve target generators, not replace with their generated targets.

    :param targets: The unexpanded targets to get data for.
    :param subsys: The `PeekSubsystem` instance.
    :return: A mapping of target addresses to their data.
    """
    sorted_targets = sorted(targets, key=lambda tgt: tgt.address)

    # We "hydrate" sources fields with the engine, but not every target has them registered.
    targets_with_sources = [tgt for tgt in sorted_targets if tgt.has_field(SourcesField)]

    # Dependency rules are described in terms of the dependency targets, which bulk
    # implementations do not produce.
    bulk_request_types = (
        () if subsys.include_dep_rules else union_membership.get(PeekBulkDependenciesRequest)
    )
    bulk_candidates: set[Address] = set()
    bulk_requests = []
    for request_type in bulk_request_types:
        candidates = tuple(
            tgt
            for tgt in request_type.candidates(sorted_targets, union_membership)
            if tgt.address not in bulk_candidates
        )
        bulk_candidates.update(tgt.address for tgt in candidates)
        if candidates:
            bulk_requests.append(request_type(candidates))

    # Other targets are resolved in bulk generically, running their dependency inference.
    generic_candidates = (
        ()
        if subsys.include_dep_rules
        else tuple(tgt for tgt in sorted_targets if tgt.address not in bulk_candidates)
    )
    bulk_candidates.update(tgt.address for tgt in generic_candidates)
    # Resolved in groups by the kinds of inference that apply, so that targets with fast (or no)
    # inference need not wait for targets whose inference is slow (e.g. runs JVM processes).
    inference_request_types = union_membership.get(InferDependenciesRequest)
    generic_groups: dict[tuple[type[InferDependenciesRequest], ...], list[Target]] = (
        collections.defaultdict(list)
    )
    inference_field_set_types = tuple(
        inference_request_type.infer_from for inference_request_type in inference_request_types
    )
    for tgt in generic_candidates:
        applicable = set(applicable_field_set_types(inference_field_set_types, tgt))
        generic_groups[
            tuple(
                inference_request_type
                for inference_request_type in inference_request_types
                if inference_request_type.infer_from in applicable
            )
        ].append(tgt)

    # When determining dependencies, we replace target generators with their generated targets.
    # The requests are grouped by target type, each group with its own bound on in-flight
    # requests, so that one slow kind of target (e.g. JVM targets waiting on a JDK download) cannot
    # monopolize them. Within a group, sorted order keeps neighbouring targets together.
    indices_by_type: dict[type[Target], list[int]] = collections.defaultdict(list)
    for i, tgt in enumerate(sorted_targets):
        if tgt.address not in bulk_candidates:
            indices_by_type[type(tgt)].append(i)
    (
        bulk_results,
        generic_results,
        dependencies_per_type,
        expanded_sources_map,
    ) = await concurrently(
        concurrently(
                get_peek_bulk_dependencies(
                    **implicitly({bulk_request: PeekBulkDependenciesRequest})
                )
                for bulk_request in bulk_requests
            ),
        concurrently(
                resolve_dependencies_bulk(
                    BulkDependenciesRequest(
                        tuple(group), FrozenDict(), inference_types=inference_types
                    ),
                    **implicitly(),
                )
                for inference_types, group in generic_groups.items()
            ),
        concurrently(
                concurrently(
                    resolve_targets(
                        **implicitly(
                            DependenciesRequest(
                                sorted_targets[i].get(Dependencies),
                                should_traverse_deps_predicate=AlwaysTraverseDeps(),
                            )
                        )
                    )
                    for i in indices
                )
                for indices in indices_by_type.values()
            ),
        # Hydrating a sources field without codegen is snapshotting its globs, so all are
        # snapshotted at once.
        _validated_sources(
                targets_with_sources,
                path_globs_to_snapshots(
                    PathGlobsBatch(
                        tuple(
                            tgt[SourcesField].path_globs(unmatched_build_file_globs)
                            for tgt in targets_with_sources
                        )
                    )
                ),
            ),
    )
    dependencies_per_target: list[Targets] = [Targets()] * len(sorted_targets)
    for indices, deps_for_type in zip(indices_by_type.values(), dependencies_per_type):
        for i, deps in zip(indices, deps_for_type):
            dependencies_per_target[i] = deps

    generic_dependencies: dict[Address, Addresses] = {}
    for generic_result in generic_results:
        generic_dependencies.update(generic_result.dependencies)
    unexpanded_bulk_dependencies: dict[Address, Addresses] = dict(generic_dependencies)
    for bulk_result in bulk_results:
        unexpanded_bulk_dependencies.update(bulk_result.dependencies)

    # Expand the bulk results as `resolve_targets` would: when no dependency is a target
    # generator, that is the identity.
    bulk_dependencies: dict[Address, Addresses] = {}
    targets_by_address = {tgt.address: tgt for tgt in sorted_targets}

    expanding_to_themselves = {
        address
        for address, tgt in targets_by_address.items()
        if address.is_generated_target or not target_types_to_generate_requests.is_generator(tgt)
    }

    needs_expansion = []
    for address, addresses in unexpanded_bulk_dependencies.items():
        if expanding_to_themselves.issuperset(addresses):
            bulk_dependencies[address] = addresses
        else:
            needs_expansion.append((address, addresses))

    declined = [
        i
        for i, tgt in enumerate(sorted_targets)
        if tgt.address in bulk_candidates and tgt.address not in unexpanded_bulk_dependencies
    ]
    # Expand in bulk the dependencies which are all targets peek already has; others individually.
    expand_locally = {
        address: [targets_by_address[dep] for dep in addresses]
        for address, addresses in needs_expansion
        if all(dep in targets_by_address for dep in addresses)
    }
    needs_expansion = [entry for entry in needs_expansion if entry[0] not in expand_locally]
    locally_expanded = await expand_targets_in_bulk(
        expand_locally, target_types_to_generate_requests, local_environment_name
    )
    for address, expanded in locally_expanded.items():
        bulk_dependencies[address] = Addresses(tgt.address for tgt in expanded)

    declined_dependencies, expanded_dependencies = await concurrently(
        concurrently(
            resolve_targets(
                **implicitly(
                    DependenciesRequest(
                        sorted_targets[i].get(Dependencies),
                        should_traverse_deps_predicate=AlwaysTraverseDeps(),
                    )
                )
            )
            for i in declined
        ),
        concurrently(
            resolve_targets(**implicitly({addresses: Addresses}))
            for _, addresses in needs_expansion
        ),
    )
    for i, deps in zip(declined, declined_dependencies):
        dependencies_per_target[i] = deps
    index_by_address = {tgt.address: i for i, tgt in enumerate(sorted_targets)}
    for (address, _), deps in zip(needs_expansion, expanded_dependencies):
        dependencies_per_target[index_by_address[address]] = deps
    if subsys.include_additional_info:
        additional_info_field_sets = [
            field_set_type.create(tgt)
            for tgt in sorted_targets
            for field_set_type in union_membership[HasAdditionalTargetDataFieldSet]
            if field_set_type.is_applicable(tgt)
        ]
        additional_infos = await concurrently(
            get_additional_target_data(**implicitly({field_set: HasAdditionalTargetDataFieldSet}))
            for field_set in additional_info_field_sets
        )
        group_additional_infos_by_address_builder = collections.defaultdict(list)
        for field_set, additional_info in zip(additional_info_field_sets, additional_infos):
            group_additional_infos_by_address_builder[field_set.address].append(additional_info)
        group_additional_infos_by_address = {
            address: tuple(additional_info)
            for address, additional_info in group_additional_infos_by_address_builder.items()
        }
    else:
        group_additional_infos_by_address = {}

    specs: dict[Address, str] = {}

    def spec(address: Address) -> str:
        address_spec = specs.get(address)
        if address_spec is None:
            address_spec = specs[address] = address.spec
        return address_spec

    expanded_dependencies = [
        tuple(spec(dep) for dep in bulk_dependencies[tgt.address])
        if tgt.address in bulk_dependencies
        else tuple(spec(dep.address) for dep in deps)
        for tgt, deps in zip(sorted_targets, dependencies_per_target)
    ]

    dependencies_rules_map: dict[Address, tuple[str, ...] | None] = {}
    dependents_rules_map: dict[Address, tuple[str, ...] | None] = {}
    applicable_dep_rules_map = {}

    if subsys.include_dep_rules:
        # TODO: Why are we pulling a private definition from `build_files`?
        family_adaptors = await _get_target_family_and_adaptor_for_dep_rules(
            *(tgt.address for tgt in sorted_targets),
            description_of_origin="`peek` goal",
        )

        dependencies_rules_map = {
            tgt.address: describe_ruleset(
                family.dependencies_rules.get_ruleset(tgt.address, adaptor)
            )
            for tgt, (family, adaptor) in zip(sorted_targets, family_adaptors)
            if family.dependencies_rules is not None
        }

        dependents_rules_map = {
            tgt.address: describe_ruleset(family.dependents_rules.get_ruleset(tgt.address, adaptor))
            for tgt, (family, adaptor) in zip(sorted_targets, family_adaptors)
            if family.dependents_rules is not None
        }

        all_applicable_dep_rules = await concurrently(
            get_dependencies_rule_application(
                DependenciesRuleApplicationRequest(
                    tgt.address,
                    Addresses(dep.address for dep in deps),
                    description_of_origin="`peek` goal",
                ),
                **implicitly(),
            )
            for tgt, deps in zip(sorted_targets, dependencies_per_target)
        )
        applicable_dep_rules_map = {
            application.address: tuple(application.dependencies_rule.values())
            for application in all_applicable_dep_rules
        }

    # TODO: This currently exists in the `goal_rule` section of code below, but I'd prefer to have it here
    # target_alias_to_goals_map = await _create_target_alias_to_goals_map() if subsys.include_goals else {}

    return TargetDatas(
        TargetData(
            tgt,
            expanded_dependencies=expanded_deps,
            expanded_sources=expanded_sources_map.get(tgt.address),
            dependencies_rules=dependencies_rules_map.get(tgt.address),
            dependents_rules=dependents_rules_map.get(tgt.address),
            applicable_dep_rules=applicable_dep_rules_map.get(tgt.address),
            goals=None,
            additional_info=group_additional_infos_by_address.get(
                tgt.address, () if subsys.include_additional_info else None
            ),
        )
        for tgt, expanded_deps in zip(sorted_targets, expanded_dependencies)
    )


async def _validated_sources(
    targets_with_sources: list[Target], snapshots_awaitable
) -> dict[Address, Snapshot]:
    snapshots = await snapshots_awaitable
    for tgt, snapshot in zip(targets_with_sources, snapshots):
        tgt[SourcesField].validate_resolved_files(snapshot.files)
    return {tgt.address: snapshot for tgt, snapshot in zip(targets_with_sources, snapshots)}


@goal_rule
async def peek(
    console: Console,
    subsys: PeekSubsystem,
    targets: UnexpandedTargets,
    union_membership: UnionMembership,
) -> Peek:
    """Display detailed target information in JSON form.

    :param console: The console to write the JSON to.
    :param subsys: The `PeekSubsystem` instance.
    :param targets: The targets to get data for.
    :return: The `Peek` goal.
    """

    # This method needs to be called in a @goal_rule, otherwise it fails out with Rule errors (when called in an @rule)
    tds, target_alias_to_goals_map = await concurrently(
        get_target_data(targets, **implicitly()),
        _create_target_alias_to_goals_map(union_membership),
    )
    output = render_json(
        tds,
        subsys.exclude_defaults,
        subsys.include_dep_rules,
        goals_by_alias=target_alias_to_goals_map or None,
    )

    with subsys.output(console) as write_stdout:
        write_stdout(output)
    return Peek(exit_code=0)


def rules() -> Iterable[Rule]:
    return collect_rules()
